=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::BingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BingApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::BingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BingApi' do
    it 'should create an instance of BingApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::BingApi)
    end
  end

  # unit tests for bing_bing_scraper_health_check
  # Bing scraper health check
  # Check health of the Bing scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'bing_bing_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_bing_scraper_health_check_head
  # Bing scraper health check
  # Check health of the Bing scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'bing_bing_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_image_search
  # Image search
  # Bing Images — thumbnail, full-size and source URL per result.
  # @param query Search keywords, e.g. &#39;golden retriever&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Bing market code, e.g. &#39;en-US&#39;, &#39;en-GB&#39;, &#39;de-DE&#39;. See /markets.
  # @option opts [Integer] :count Results to return
  # @option opts [String] :safe_search off | moderate | strict
  # @return [Object]
  describe 'bing_image_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_list_supported_markets
  # List supported markets
  # Supported Bing market codes. Free — costs no credits.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'bing_list_supported_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_news_search
  # News search
  # Bing News — headline, source, published time and snippet per article.
  # @param query Search keywords, e.g. &#39;interest rates&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Bing market code, e.g. &#39;en-US&#39;, &#39;en-GB&#39;, &#39;de-DE&#39;. See /markets.
  # @option opts [String] :freshness day | week | month — restrict to recent articles
  # @return [Object]
  describe 'bing_news_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_search_suggestions
  # Search suggestions
  # Bing search-box query suggestions.
  # @param query Partial search term, e.g. &#39;coff&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Bing market code, e.g. &#39;en-US&#39;, &#39;en-GB&#39;, &#39;de-DE&#39;. See /markets.
  # @return [Object]
  describe 'bing_search_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_video_search
  # Video search
  # Bing Videos — title, thumbnail, duration, publisher and source per result.
  # @param query Search keywords, e.g. &#39;espresso tutorial&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Bing market code, e.g. &#39;en-US&#39;, &#39;en-GB&#39;, &#39;de-DE&#39;. See /markets.
  # @option opts [Integer] :count Results to return
  # @option opts [String] :safe_search off | moderate | strict
  # @return [Object]
  describe 'bing_video_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for bing_web_search
  # Web search
  # Bing web SERP — organic results, ads, related searches and total count.
  # @param query Search keywords, e.g. &#39;coffee machine&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Bing market code, e.g. &#39;en-US&#39;, &#39;en-GB&#39;, &#39;de-DE&#39;. See /markets.
  # @option opts [Integer] :count Results per page (1-50)
  # @option opts [Integer] :offset Zero-based result offset for pagination
  # @option opts [String] :safe_search off | moderate | strict (default moderate)
  # @return [Object]
  describe 'bing_web_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
