=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::DepopApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DepopApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::DepopApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DepopApi' do
    it 'should create an instance of DepopApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::DepopApi)
    end
  end

  # unit tests for depop_depop_scraper_health_check
  # Depop scraper health check
  # Check health of the Depop scraper service (accepts HEAD).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'depop_depop_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_depop_scraper_health_check_head
  # Depop scraper health check
  # Check health of the Depop scraper service (accepts HEAD).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'depop_depop_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_get_a_user_s_products
  # Get a user&#39;s products
  # A user&#39;s active listings (cursor-paginated).
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Market code
  # @option opts [Integer] :per_page 
  # @option opts [String] :cursor Pagination cursor
  # @return [Object]
  describe 'depop_get_a_user_s_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_get_product_detail
  # Get product detail
  # Full detail for a single product (by numeric id or slug).
  # @param product_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Market code
  # @return [Object]
  describe 'depop_get_product_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_get_shop_user_profile
  # Get shop/user profile
  # Public shop/user profile by username.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Market code
  # @return [Object]
  describe 'depop_get_shop_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_list_markets
  # List markets
  # List supported Depop markets (country + currency).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'depop_list_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for depop_search_depop_products
  # Search Depop products
  # Search the Depop catalog with filters (cursor-paginated).
  # @param query Search text, e.g. &#39;nike vintage&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market Market code (us, gb, au, it, fr, ...)
  # @option opts [Integer] :per_page Results per page
  # @option opts [String] :cursor Pagination cursor (from previous page)
  # @option opts [Float] :price_min Minimum price
  # @option opts [Float] :price_max Maximum price
  # @option opts [String] :brands Comma-separated brand IDs
  # @option opts [String] :categories Comma-separated category IDs
  # @option opts [String] :sizes Comma-separated size IDs
  # @option opts [String] :conditions Comma-separated condition slugs (brand_new, used_excellent, ...)
  # @option opts [String] :gender male | female
  # @option opts [String] :sort relevance | newlyListed | priceAscending | priceDescending
  # @return [Object]
  describe 'depop_search_depop_products test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
