=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::DuckDuckGoApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DuckDuckGoApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::DuckDuckGoApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DuckDuckGoApi' do
    it 'should create an instance of DuckDuckGoApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::DuckDuckGoApi)
    end
  end

  # unit tests for duckduckgo_duckduckgo_scraper_health_check
  # DuckDuckGo scraper health check
  # Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'duckduckgo_duckduckgo_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_duckduckgo_scraper_health_check_head
  # DuckDuckGo scraper health check
  # Check health of the DuckDuckGo scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'duckduckgo_duckduckgo_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_image_search
  # Image search
  # DuckDuckGo image search with size/color/type/layout/license filters.
  # @param query Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions.
  # @option opts [String] :safesearch on | moderate | off
  # @option opts [Integer] :page 100 results per page
  # @option opts [String] :size Small | Medium | Large | Wallpaper
  # @option opts [String] :color color | Monochrome | Red | Blue | …
  # @option opts [String] :image_type photo | clipart | gif | transparent | line
  # @option opts [String] :layout Square | Tall | Wide
  # @option opts [String] :license Any | Public | Share | ShareCommercially | Modify
  # @return [Object]
  describe 'duckduckgo_image_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_instant_answer
  # Instant Answer
  # DuckDuckGo Instant Answer — abstract, definition, direct answer, related topics.
  # @param query Query for the Instant Answer API
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'duckduckgo_instant_answer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_list_supported_regions
  # List supported regions
  # The full DuckDuckGo region (kl) code list.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'duckduckgo_list_supported_regions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_news_search
  # News search
  # DuckDuckGo news search — headline, source, excerpt, unix + ISO date, image.
  # @param query Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions.
  # @option opts [String] :safesearch on | moderate | off
  # @option opts [String] :timelimit day | week | month | year
  # @option opts [Integer] :page 30 results per page
  # @return [Object]
  describe 'duckduckgo_news_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_search_suggestions
  # Search suggestions
  # DuckDuckGo search-box suggestions.
  # @param query Partial query to complete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions.
  # @return [Object]
  describe 'duckduckgo_search_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_video_search
  # Video search
  # DuckDuckGo video search — title, publisher, uploader, duration, views, thumbnails.
  # @param query Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions.
  # @option opts [String] :safesearch on | moderate | off
  # @option opts [Integer] :page 60 results per page
  # @option opts [String] :duration short | medium | long
  # @option opts [String] :resolution high | standard
  # @return [Object]
  describe 'duckduckgo_video_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for duckduckgo_web_search
  # Web search
  # DuckDuckGo web SERP — organic results, the zero-click abstract box, ads flagged.
  # @param query Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region DuckDuckGo region code (kl), e.g. us-en, uk-en, de-de. wt-wt &#x3D; all regions.
  # @option opts [String] :safesearch on | moderate | off
  # @option opts [String] :timelimit day | week | month | year
  # @option opts [Integer] :page 
  # @return [Object]
  describe 'duckduckgo_web_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
