=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::EBayApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EBayApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::EBayApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EBayApi' do
    it 'should create an instance of EBayApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::EBayApi)
    end
  end

  # unit tests for ebay_browse_a_category
  # Browse a category
  # List active listings within an eBay category.
  # @param category_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :sort_by best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
  # @option opts [Float] :min_price 
  # @option opts [Float] :max_price 
  # @return [Object]
  describe 'ebay_browse_a_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_completed_sold_listings
  # Completed / sold listings
  # Search completed/sold listings — eBay&#39;s sold-price history.
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @option opts [String] :category_id 
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @option opts [String] :sort_by best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
  # @option opts [String] :condition new|open_box|refurbished|used|for_parts
  # @option opts [Float] :min_price 
  # @option opts [Float] :max_price 
  # @return [Object]
  describe 'ebay_completed_sold_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_ebay_scraper_health_check
  # eBay scraper health check
  # Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ebay_ebay_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_ebay_scraper_health_check_head
  # eBay scraper health check
  # Check health of the eBay scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ebay_ebay_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_get_item_detail
  # Get item detail
  # Get a single eBay listing&#39;s full detail.
  # @param item_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @return [Object]
  describe 'ebay_get_item_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_get_item_reviews
  # Get item reviews
  # Get catalog product reviews shown on an eBay listing.
  # @param item_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @option opts [Integer] :page 
  # @return [Object]
  describe 'ebay_get_item_reviews test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_get_seller_feedback
  # Get seller feedback
  # Get a seller&#39;s recent feedback comments.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @option opts [Integer] :page 
  # @return [Object]
  describe 'ebay_get_seller_feedback test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_get_seller_listings
  # Get seller listings
  # List the active listings of a single eBay seller.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @option opts [String] :query 
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 
  # @return [Object]
  describe 'ebay_get_seller_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_get_seller_profile
  # Get seller profile
  # Get an eBay seller&#39;s public profile.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @return [Object]
  describe 'ebay_get_seller_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_keyword_suggestions
  # Keyword suggestions
  # Return eBay keyword autocomplete suggestions.
  # @param query Partial query prefix
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain 
  # @return [Object]
  describe 'ebay_keyword_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_list_categories
  # List categories
  # List eBay&#39;s top-level category ids.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ebay_list_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_list_markets
  # List markets
  # List all supported eBay marketplaces.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'ebay_list_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for ebay_search_listings
  # Search listings
  # Search an eBay marketplace for active listings.
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain Marketplace domain (com, co.uk, de …)
  # @option opts [String] :category_id Restrict to a category id
  # @option opts [Integer] :page 
  # @option opts [Integer] :per_page 60, 120 or 240
  # @option opts [String] :sort_by best_match|ending_soonest|newly_listed|price_low_to_high|price_high_to_low
  # @option opts [String] :condition new|open_box|refurbished|used|for_parts
  # @option opts [String] :buying_format auction|buy_it_now|best_offer
  # @option opts [Float] :min_price 
  # @option opts [Float] :max_price 
  # @option opts [Boolean] :free_shipping 
  # @return [Object]
  describe 'ebay_search_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
