=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::FacebookApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FacebookApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::FacebookApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FacebookApi' do
    it 'should create an instance of FacebookApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::FacebookApi)
    end
  end

  # unit tests for facebook_browse_a_marketplace_category
  # Browse a Marketplace category
  # Browse Marketplace listings in a category (vehicles, electronics, ...).
  # @param category 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :location 
  # @option opts [Integer] :min_price 
  # @option opts [Integer] :max_price 
  # @option opts [String] :sort_by 
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_browse_a_marketplace_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_a_marketplace_item
  # Get a Marketplace item
  # Get full detail for a single Marketplace listing.
  # @param item_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_get_a_marketplace_item test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_advertiser_page_info
  # Get advertiser page info
  # Get advertiser page info: category, followers, page transparency (creation date, name history, managing organization, admin-account locations), related pages, and ad spend (for political/issue advertisers).
  # @param page_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country 
  # @return [Object]
  describe 'facebook_get_advertiser_page_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_an_ad
  # Get an ad
  # Get a single Ad Library ad by its archive id. For EU/UK-targeted ads the response also includes transparency insights (payer/beneficiary, total EU reach, and age/gender/country reach breakdowns).
  # @param ad_archive_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country ISO country code (an EU code returns EU transparency)
  # @return [Object]
  describe 'facebook_get_an_ad test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_group_detail
  # Get group detail
  # Get a Facebook group&#39;s details.
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_get_group_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_group_posts
  # Get group posts
  # Get a Facebook group&#39;s post feed.
  # @param group_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_get_group_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_page_detail
  # Get page detail
  # Get a Facebook Page&#39;s profile (name, category, followers, about).
  # @param identifier 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_get_page_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_page_posts
  # Get page posts
  # Get a Facebook Page&#39;s timeline posts.
  # @param identifier 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_get_page_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_post_comments
  # Get post comments
  # Get a Facebook post&#39;s comment thread, 10 per page.  &#x60;&#x60;sort&#x60;&#x60; is &#x60;&#x60;relevance&#x60;&#x60; (Facebook&#39;s ranked order, the default) or &#x60;&#x60;newest&#x60;&#x60;. Follow &#x60;&#x60;end_cursor&#x60;&#x60; while &#x60;&#x60;has_next_page&#x60;&#x60; to walk the whole thread; &#x60;&#x60;total_count&#x60;&#x60; is how many the post has.
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url Full post permalink/reel URL — overrides post_id
  # @option opts [String] :after 
  # @option opts [String] :sort relevance | newest
  # @return [Object]
  describe 'facebook_get_post_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_post_detail
  # Get post detail
  # Get a Facebook post&#39;s detail: text, media, author, date and the reaction / comment / share counts. The comments themselves come from &#x60;&#x60;/posts/{post_id}/comments&#x60;&#x60;.
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url Full post permalink/reel URL — overrides post_id
  # @return [Object]
  describe 'facebook_get_post_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_profile_detail
  # Get profile detail
  # Get a Facebook profile&#39;s details.
  # @param identifier 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_get_profile_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_get_profile_posts
  # Get profile posts
  # Get a Facebook profile&#39;s timeline posts.
  # @param identifier 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_get_profile_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_list_categories
  # List categories
  # List Marketplace category slugs (free).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_list_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_list_locations
  # List locations
  # List common Marketplace location slugs (free).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'facebook_list_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_advertiser_pages
  # Search advertiser pages
  # Search advertiser Pages in the Ad Library — returns page ids, categories, likes/followers, verification and Instagram handles.
  # @param query Advertiser name or keyword
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country 
  # @return [Object]
  describe 'facebook_search_advertiser_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_events
  # Search events
  # Search Facebook events.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_events test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_everything
  # Search everything
  # Global Facebook search (top results across pages, people, groups, posts).
  # @param q Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_everything test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_groups
  # Search groups
  # Search Facebook groups.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_groups test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_marketplace
  # Search Marketplace
  # Search Facebook Marketplace listings by keyword and location.  &#x60;&#x60;location&#x60;&#x60; must be a Facebook location slug (&#x60;&#x60;london&#x60;&#x60;, &#x60;&#x60;newcastleupontyne&#x60;&#x60;) or a numeric Facebook place id — the &#x60;&#x60;city_page_id&#x60;&#x60; on any listing is one. Human-readable names such as &#x60;&#x60;Durham, UK&#x60;&#x60; are rejected with a 400 rather than silently searching Facebook&#39;s San Francisco default.
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @option opts [String] :location Marketplace location slug or numeric place id
  # @option opts [Integer] :min_price 
  # @option opts [Integer] :max_price 
  # @option opts [Integer] :days_since_listed 
  # @option opts [String] :sort_by 
  # @option opts [String] :item_condition 
  # @option opts [String] :delivery_method 
  # @option opts [Integer] :radius Search radius around the location (km, or miles in the US)
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_marketplace test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_pages
  # Search Pages
  # Search Facebook Pages.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_people
  # Search people
  # Search Facebook profiles.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_people test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_places
  # Search places
  # Search Facebook places.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_places test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_posts
  # Search posts
  # Search public Facebook posts.
  # @param q 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for facebook_search_the_ad_library
  # Search the Ad Library
  # Search the Facebook Ad Library.
  # @param query Advertiser or keyword
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country 
  # @option opts [String] :ad_type 
  # @option opts [String] :active_status 
  # @option opts [String] :after 
  # @return [Object]
  describe 'facebook_search_the_ad_library test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
