=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::GooglePlayApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GooglePlayApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::GooglePlayApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GooglePlayApi' do
    it 'should create an instance of GooglePlayApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::GooglePlayApi)
    end
  end

  # unit tests for google_play_browse_a_category
  # Browse a category
  # The top apps within a Play category.
  # @param category_id Play category id, e.g. &#39;GAME_PUZZLE&#39; or &#39;SOCIAL&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @option opts [Integer] :num Max apps; follows each rail&#39;s &#39;see more&#39; continuation above the ~40-120 the page renders directly
  # @return [Object]
  describe 'google_play_browse_a_category test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_get_app_detail
  # Get app detail
  # Full app detail: ratings histogram, installs, pricing, IAP, developer, screenshots, version metadata and what&#39;s-new.
  # @param app_id Android package id, e.g. &#39;com.whatsapp&#39;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @return [Object]
  describe 'google_play_get_app_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_get_app_permissions
  # Get app permissions
  # The app&#39;s requested Android permissions, grouped.
  # @param app_id Android package id, e.g. &#39;com.whatsapp&#39;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @return [Object]
  describe 'google_play_get_app_permissions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_get_app_reviews
  # Get app reviews
  # Paginated app reviews via the Play batchexecute RPC.
  # @param app_id Android package id, e.g. &#39;com.whatsapp&#39;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @option opts [String] :sort newest | rating | helpfulness
  # @option opts [Integer] :count 
  # @option opts [String] :page_token Pagination token
  # @return [Object]
  describe 'google_play_get_app_reviews test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_get_developer_apps
  # Get developer apps
  # A developer&#39;s published apps.
  # @param developer Developer name or numeric id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @option opts [Integer] :num Max apps; follows rail continuations above the page&#39;s directly-rendered slice
  # @return [Object]
  describe 'google_play_get_developer_apps test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_get_similar_apps
  # Get similar apps
  # Apps Google Play lists as similar to this one.
  # @param app_id Android package id, e.g. &#39;com.whatsapp&#39;.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @return [Object]
  describe 'google_play_get_similar_apps test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_list_categories
  # List categories
  # The Google Play app/game category ids.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'google_play_list_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_list_markets
  # List markets
  # Supported Google Play store countries and languages.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'google_play_list_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_search_apps
  # Search apps
  # Search Google Play for apps and games (the ~30 server-rendered results; Play exposes no page parameter).
  # @param query Search keywords, e.g. &#39;puzzle&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @option opts [String] :price free | paid | all
  # @return [Object]
  describe 'google_play_search_apps test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for google_play_top_charts
  # Top charts
  # Top charts for a collection, optionally scoped to a category.
  # @param collection topselling_free | topselling_paid | topgrossing
  # @param [Hash] opts the optional parameters
  # @option opts [String] :category Play category, e.g. &#39;GAME&#39;
  # @option opts [String] :country Play storefront country (gl), ISO 3166-1 alpha-2, e.g. &#39;US&#39;
  # @option opts [String] :lang Play content language (hl), e.g. &#39;en&#39; or &#39;pt-BR&#39;
  # @return [Object]
  describe 'google_play_top_charts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
