=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::IdealistaApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IdealistaApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::IdealistaApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdealistaApi' do
    it 'should create an instance of IdealistaApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::IdealistaApi)
    end
  end

  # unit tests for idealista_agency_by_phone
  # Agency by phone
  # Reverse-lookup the agency behind a contact phone (national number), with its listings.
  # @param phone 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market es|it|pt
  # @option opts [String] :operation sale|rent
  # @option opts [String] :property_type homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
  # @option opts [Integer] :page 
  # @option opts [Integer] :max_items 
  # @option opts [Boolean] :include_listings 
  # @return [Object]
  describe 'idealista_agency_by_phone test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_agency_profile_listings
  # Agency profile + listings
  # An agency&#39;s microsite profile plus a page of its listings (by URL-slug shortName).
  # @param short_name 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market es|it|pt
  # @option opts [String] :operation sale|rent
  # @option opts [String] :property_type homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
  # @option opts [Integer] :page 
  # @option opts [Integer] :max_items 
  # @option opts [Boolean] :include_listings 
  # @return [Object]
  describe 'idealista_agency_profile_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_get_listing_engagement_stats
  # Get listing engagement stats
  # Engagement counters for a listing: views, email contacts, sent-to-friend, favourites.
  # @param property_code 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market es|it|pt
  # @option opts [String] :locale Language for stat labels
  # @return [Object]
  describe 'idealista_get_listing_engagement_stats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_get_property_detail
  # Get property detail
  # Get a single Idealista listing&#39;s full detail (energy cert, characteristics, media).
  # @param property_code 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :market es|it|pt
  # @option opts [String] :locale Response language (en, es, it, pt)
  # @return [Object]
  describe 'idealista_get_property_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_idealista_scraper_health_check
  # Idealista scraper health check
  # Check health of the Idealista scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'idealista_idealista_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_idealista_scraper_health_check_head
  # Idealista scraper health check
  # Check health of the Idealista scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'idealista_idealista_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_list_markets
  # List markets
  # List supported Idealista markets (ES, IT, PT).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'idealista_list_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_resolve_locations
  # Resolve locations
  # Resolve a free-text query into Idealista location codes for a search.
  # @param query Free-text location, e.g. &#39;sagrada familia&#39;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :operation sale|rent
  # @option opts [String] :property_type homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
  # @option opts [String] :market es|it|pt
  # @option opts [String] :locale Response language (en, es, it, pt)
  # @return [Object]
  describe 'idealista_resolve_locations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_search_all_beats_result_cap
  # Search all (beats result cap)
  # Full inventory for a location, beating Idealista&#39;s ~1800 per-search cap via price-range tiling (deduped). Billed per page fetched.
  # @param location Idealista location code (from /suggest)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :operation sale|rent
  # @option opts [String] :property_type homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
  # @option opts [String] :market es|it|pt
  # @option opts [Integer] :max_results 
  # @option opts [Float] :min_price 
  # @option opts [Float] :max_price 
  # @option opts [Float] :min_size 
  # @option opts [Float] :max_size 
  # @option opts [Integer] :min_rooms 
  # @option opts [Integer] :max_rooms 
  # @option opts [String] :locale Response language (en, es, it, pt)
  # @return [Object]
  describe 'idealista_search_all_beats_result_cap test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for idealista_search_listings
  # Search listings
  # Search Idealista real-estate listings by location code.
  # @param location Idealista location code (from /suggest)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :operation sale|rent
  # @option opts [String] :property_type homes|offices|premises|garages|newDevelopments|lands|storageRooms|buildings|bedrooms
  # @option opts [String] :market es|it|pt
  # @option opts [Integer] :page 
  # @option opts [Integer] :max_items 
  # @option opts [String] :sort_by distance|size|rooms|floor|ratioeurm2|price|street|photos|modificationDate|publicationDate|weigh|priceDown|preservationTypeAndPrice|privateAds
  # @option opts [String] :sort_order asc|desc
  # @option opts [Float] :min_price 
  # @option opts [Float] :max_price 
  # @option opts [Float] :min_size 
  # @option opts [Float] :max_size 
  # @option opts [Integer] :min_rooms 
  # @option opts [Integer] :max_rooms 
  # @option opts [String] :locale Response language (en, es, it, pt)
  # @return [Object]
  describe 'idealista_search_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
