=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::InstagramApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InstagramApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::InstagramApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InstagramApi' do
    it 'should create an instance of InstagramApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::InstagramApi)
    end
  end

  # unit tests for instagram_about_this_account
  # About this account
  # Country, join date and former usernames.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_about_this_account test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_blended_top_search
  # Blended top search
  # @param query 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_blended_top_search test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_active_stories
  # Get active stories
  # Active stories (account pool only).
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_active_stories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_audio_track
  # Get audio track
  # @param audio_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_audio_track test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_comments
  # Get comments
  # @param code 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_get_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_followers
  # Get followers
  # Followers list, paginated (account pool).
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @option opts [String] :order date_followed_latest | date_followed_earliest
  # @return [Object]
  describe 'instagram_get_followers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_following
  # Get following
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_get_following test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_hashtag_info
  # Get hashtag info
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_hashtag_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_highlights
  # Get highlights
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_highlights test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_likers
  # Get likers
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_likers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_location
  # Get location
  # @param location_pk 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_location test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_post_reel_detail
  # Get post/reel detail
  # Single post or reel: caption, media, counts, tags, location, carousel.
  # @param code 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_post_reel_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_profile
  # Get profile
  # Full public profile: bio, counts, verification, business contact, links.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_get_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_tagged_posts
  # Get tagged posts
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_get_tagged_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_user_posts
  # Get user posts
  # Timeline posts, paginated.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_get_user_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_get_user_reels
  # Get user reels
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_get_user_reels test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_health
  # Health
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_health test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_health_head
  # Health
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_health_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_recent_hashtag_posts
  # Recent hashtag posts
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_recent_hashtag_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_related_profiles
  # Related profiles
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_related_profiles test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_search_hashtags
  # Search hashtags
  # @param query 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_search_hashtags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_search_users
  # Search users
  # @param query 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'instagram_search_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for instagram_top_hashtag_posts
  # Top hashtag posts
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :amount 
  # @option opts [String] :cursor 
  # @return [Object]
  describe 'instagram_top_hashtag_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
