=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::PerplexityApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PerplexityApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::PerplexityApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PerplexityApi' do
    it 'should create an instance of PerplexityApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::PerplexityApi)
    end
  end

  # unit tests for perplexity_ask_perplexity_a_question
  # Ask Perplexity a question
  # Send a prompt to Perplexity and get the answer plus the web sources it cited.
  # @param prompt The prompt to send to Perplexity (max 4096 characters).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :country ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;.
  # @return [Object]
  describe 'perplexity_ask_perplexity_a_question test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for perplexity_ask_perplexity_a_question_post
  # Ask Perplexity a question (POST)
  # POST form of &#x60;/ask&#x60;, for prompts too long for a query string.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'perplexity_ask_perplexity_a_question_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for perplexity_measure_a_brand_s_visibility_in_a_perplexity_answer
  # Measure a brand&#39;s visibility in a Perplexity answer
  # Ask Perplexity, then report whether the brand is mentioned, cited and how prominently.
  # @param prompt The prompt to ask Perplexity.
  # @param brand Brand name to look for in the answer.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :domain Brand domain, for citation matching.
  # @option opts [String] :aliases Comma-separated alternative names.
  # @option opts [String] :competitors Comma-separated competitor names.
  # @option opts [String] :country ISO-3166 alpha-2 egress country.
  # @return [Object]
  describe 'perplexity_measure_a_brand_s_visibility_in_a_perplexity_answer test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for perplexity_measure_a_brand_s_visibility_in_a_perplexity_answer_post
  # Measure a brand&#39;s visibility in a Perplexity answer (POST)
  # POST form, for longer prompts and larger competitor sets.
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'perplexity_measure_a_brand_s_visibility_in_a_perplexity_answer_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for perplexity_perplexity_scraper_health_check
  # Perplexity scraper health check
  # Check health of the Perplexity scraper service (accepts HEAD).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'perplexity_perplexity_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for perplexity_perplexity_scraper_health_check_head
  # Perplexity scraper health check
  # Check health of the Perplexity scraper service (accepts HEAD).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'perplexity_perplexity_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
