=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::RedditApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RedditApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::RedditApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedditApi' do
    it 'should create an instance of RedditApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::RedditApi)
    end
  end

  # unit tests for reddit_get_cross_posts
  # Get cross-posts
  # Get cross-posts and duplicates of a Reddit post.
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_cross_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_post_comments
  # Get post comments
  # Get comment tree for a Reddit post.
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Sort: confidence, top, new, controversial, old, qa
  # @option opts [Integer] :limit 
  # @option opts [Integer] :depth 
  # @return [Object]
  describe 'reddit_get_post_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_post_detail
  # Get post detail
  # Get detailed information about a Reddit post.
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_post_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_posts_by_domain
  # Get posts by domain
  # Get Reddit posts linking to a specific domain.
  # @param domain 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort 
  # @option opts [String] :t 
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_posts_by_domain test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_subreddit_info
  # Get subreddit info
  # Get detailed information about a subreddit.
  # @param subreddit 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_subreddit_info test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_subreddit_posts
  # Get subreddit posts
  # Get posts from a subreddit with sorting options.
  # @param subreddit 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Sort: hot, new, top, rising, controversial
  # @option opts [String] :t Time filter
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_subreddit_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_subreddit_rules
  # Get subreddit rules
  # Get the rules of a subreddit.
  # @param subreddit 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_subreddit_rules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_trending_posts
  # Get trending posts
  # Get trending posts from Reddit&#39;s front page.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort Sort: hot, new, top, rising, controversial, best
  # @option opts [String] :t Time filter
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_trending_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_user_profile
  # Get user profile
  # Get a Reddit user&#39;s profile.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_user_s_comments
  # Get user&#39;s comments
  # Get comments by a Reddit user.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort 
  # @option opts [String] :t 
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_user_s_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_user_s_moderated_subreddits
  # Get user&#39;s moderated subreddits
  # Get subreddits moderated by a user.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_user_s_moderated_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_user_s_posts
  # Get user&#39;s posts
  # Get posts submitted by a Reddit user.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort 
  # @option opts [String] :t 
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_get_user_s_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_user_s_trophies
  # Get user&#39;s trophies
  # Get a user&#39;s trophy case.
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_user_s_trophies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_get_wiki_page_content
  # Get wiki page content
  # Get the content of a specific wiki page.
  # @param subreddit 
  # @param page 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_get_wiki_page_content test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_list_wiki_pages
  # List wiki pages
  # List all wiki pages in a subreddit.
  # @param subreddit 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_list_wiki_pages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_new_subreddits
  # New subreddits
  # Get recently created subreddits.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_new_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_popular_subreddits
  # Popular subreddits
  # Get popular subreddits by subscriber count.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_popular_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_reddit_scraper_health_check
  # Reddit scraper health check
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_reddit_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_reddit_scraper_health_check_head
  # Reddit scraper health check
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'reddit_reddit_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_search_reddit_posts
  # Search Reddit posts
  # Search Reddit posts globally or within a subreddit.
  # @param q Search query
  # @param [Hash] opts the optional parameters
  # @option opts [String] :subreddit Restrict to subreddit
  # @option opts [String] :sort Sort: relevance, hot, top, new, comments
  # @option opts [String] :t Time: hour, day, week, month, year, all
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_search_reddit_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_search_subreddits
  # Search subreddits
  # Search for subreddits by keyword.
  # @param q Search query
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_search_subreddits test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reddit_search_users
  # Search users
  # Search for Reddit users.
  # @param q Search query
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :after 
  # @return [Object]
  describe 'reddit_search_users test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
