=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::RedfinApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RedfinApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::RedfinApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RedfinApi' do
    it 'should create an instance of RedfinApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::RedfinApi)
    end
  end

  # unit tests for redfin_get_agent_profile_listings
  # Get agent profile + listings
  # Get a Redfin real-estate agent&#39;s profile and their active listings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :url Full Redfin /realestateagents/ URL
  # @option opts [String] :agent_id Redfin agent id
  # @return [Object]
  describe 'redfin_get_agent_profile_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_get_property_detail
  # Get property detail
  # Get a single Redfin property&#39;s full detail by its numeric propertyId.
  # @param property_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_get_property_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_get_property_detail_by_url
  # Get property detail by URL
  # Get a single Redfin property&#39;s full detail by its home URL.
  # @param url Full Redfin property URL (/CA/City/.../home/12345678)
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_get_property_detail_by_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_list_coverage_markets
  # List coverage markets
  # List Redfin coverage regions (US).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_list_coverage_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_redfin_scraper_health_check
  # Redfin scraper health check
  # Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_redfin_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_redfin_scraper_health_check_head
  # Redfin scraper health check
  # Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_redfin_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_region_address_suggestions
  # Region/address suggestions
  # Resolve a search term to Redfin regions/addresses.
  # @param query Partial location — city, ZIP, address, neighborhood
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'redfin_region_address_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for redfin_search_properties
  # Search properties
  # Search Redfin for for-sale / for-rent / recently-sold properties.
  # @param location City/state, ZIP, address or neighborhood
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :sort relevant|newest|price_high_to_low|price_low_to_high|square_feet|lot_size|price_per_sqft|beds|baths
  # @option opts [Integer] :price_min 
  # @option opts [Integer] :price_max 
  # @option opts [Integer] :beds_min 
  # @option opts [Float] :baths_min 
  # @option opts [String] :home_type house|condo|townhouse|multi_family|land|mobile|coop|other
  # @option opts [Integer] :sqft_min 
  # @option opts [Integer] :sqft_max 
  # @option opts [Integer] :lot_min 
  # @option opts [Integer] :lot_max 
  # @option opts [Integer] :year_built_min 
  # @option opts [Integer] :year_built_max 
  # @option opts [Integer] :max_days_on_market 
  # @option opts [Float] :north Map bounds for tiling past the cap
  # @option opts [Float] :south 
  # @option opts [Float] :east 
  # @option opts [Float] :west 
  # @return [Object]
  describe 'redfin_search_properties test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
