=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::YouTubeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'YouTubeApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::YouTubeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of YouTubeApi' do
    it 'should create an instance of YouTubeApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::YouTubeApi)
    end
  end

  # unit tests for youtube_batch_video_detail
  # Batch video detail
  # @param request_body 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_batch_video_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_channel_about
  # Channel about
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_channel_about test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_channel_playlists
  # Channel playlists
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_channel_playlists test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_channel_shorts
  # Channel shorts
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_channel_shorts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_channel_streams
  # Channel streams
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_channel_streams test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_channel_videos
  # Channel videos
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_channel_videos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_comment_replies
  # Comment replies
  # @param video_id 
  # @param comment_id 
  # @param continuation Replies continuation token
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_comment_replies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_community_post_comments
  # Community post comments
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_community_post_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_community_posts
  # Community posts
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_community_posts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_content_regions
  # Content regions
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_content_regions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_a_community_post
  # Get a community post
  # @param post_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_get_a_community_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_a_mix_radio_queue
  # Get a mix / radio queue
  # @param playlist_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_get_a_mix_radio_queue test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_a_short
  # Get a Short
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_get_a_short test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_channel_detail
  # Get channel detail
  # Channel detail (accepts a UC id, @handle, or custom URL).
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gl 
  # @option opts [String] :hl 
  # @return [Object]
  describe 'youtube_get_channel_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_playlist_detail
  # Get playlist detail
  # @param playlist_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_get_playlist_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_get_video_detail
  # Get video detail
  # Full video detail — merged player + next (likes, comments, chapters, related).
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gl 
  # @option opts [String] :hl 
  # @return [Object]
  describe 'youtube_get_video_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_guest_home_feed
  # Guest home feed
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_guest_home_feed test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_keyword_suggestions
  # Keyword suggestions
  # Return YouTube keyword autocomplete suggestions.
  # @param query Partial query prefix
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gl 
  # @option opts [String] :hl 
  # @return [Object]
  describe 'youtube_keyword_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_list_caption_tracks
  # List caption tracks
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_list_caption_tracks test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_live_chat_messages
  # Live chat messages
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :continuation 
  # @option opts [Boolean] :replay 
  # @return [Object]
  describe 'youtube_live_chat_messages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_oembed_metadata
  # oEmbed metadata
  # @param url A YouTube URL
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_oembed_metadata test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_playlist_items_page
  # Playlist items page
  # @param playlist_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_playlist_items_page test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_related_videos
  # Related videos
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_related_videos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_resolve_handle_url_to_id
  # Resolve handle/URL to id
  # @param [Hash] opts the optional parameters
  # @option opts [String] :handle 
  # @option opts [String] :url 
  # @return [Object]
  describe 'youtube_resolve_handle_url_to_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_search_within_a_channel
  # Search within a channel
  # @param channel_id 
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_search_within_a_channel test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_search_youtube
  # Search YouTube
  # Search videos / channels / playlists with the full filter matrix.
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @option opts [String] :type video|channel|playlist|movie|all
  # @option opts [String] :sort_by relevance|date|views|rating
  # @option opts [String] :upload_date hour|today|week|month|year
  # @option opts [String] :duration short|medium|long
  # @option opts [String] :features hd,4k,360,vr180,3d,hdr,cc,subtitles,live
  # @option opts [String] :gl Content region (US, GB, DE…)
  # @option opts [String] :hl UI language
  # @option opts [String] :continuation 
  # @return [Object]
  describe 'youtube_search_youtube test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_search_youtube_music
  # Search YouTube Music
  # @param query Search keywords
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_search_youtube_music test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_shorts_by_sound
  # Shorts by sound
  # @param sound_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_shorts_by_sound test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_stream_formats
  # Stream formats
  # Stream/format metadata (best-effort; media URLs may be PO-token gated).
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :client IOS|ANDROID|WEB
  # @return [Object]
  describe 'youtube_stream_formats test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_subscriber_count_fast
  # Subscriber count (fast)
  # @param channel_id 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_subscriber_count_fast test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_supported_markets
  # Supported markets
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_supported_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_trending_shorts
  # Trending shorts
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_trending_shorts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_trending_videos
  # Trending videos
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gl 
  # @option opts [String] :type now|music|gaming|movies
  # @return [Object]
  describe 'youtube_trending_videos test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_ui_languages
  # UI languages
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_ui_languages test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_video_categories
  # Video categories
  # @param [Hash] opts the optional parameters
  # @option opts [String] :gl 
  # @return [Object]
  describe 'youtube_video_categories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_video_comments
  # Video comments
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :sort_by top|newest
  # @option opts [String] :continuation 
  # @return [Object]
  describe 'youtube_video_comments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_video_transcript
  # Video transcript
  # @param video_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :language BCP-47 language code
  # @return [Object]
  describe 'youtube_video_transcript test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_videos_under_a_hashtag
  # Videos under a hashtag
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_videos_under_a_hashtag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_youtube_scraper_health_check
  # YouTube scraper health check
  # Check health of the YouTube scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_youtube_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for youtube_youtube_scraper_health_check_head
  # YouTube scraper health check
  # Check health of the YouTube scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'youtube_youtube_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
