=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ScrapeBadger::ZillowApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ZillowApi' do
  before do
    # run before each test
    @api_instance = ScrapeBadger::ZillowApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ZillowApi' do
    it 'should create an instance of ZillowApi' do
      expect(@api_instance).to be_instance_of(ScrapeBadger::ZillowApi)
    end
  end

  # unit tests for zillow_get_agent_profile_listings
  # Get agent profile + listings
  # Get a Zillow professional&#39;s profile and their active listings.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :username Zillow profile username
  # @option opts [String] :url Full Zillow /profile/... URL
  # @return [Object]
  describe 'zillow_get_agent_profile_listings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_get_multifamily_building
  # Get multifamily building
  # Get a Zillow apartment community with per-unit pricing and availability.  Multi-unit rentals are served on &#x60;/apartments/...&#x60; and &#x60;/b/...&#x60; pages, which &#x60;/property&#x60; cannot read — pass a &#x60;home_type&#x3D;BUILDING&#x60; search result&#39;s &#x60;detail_url&#x60; here instead.
  # @param url Full Zillow building URL, e.g. https://www.zillow.com/apartments/kansas-city-mo/brookside-51/CkBJqt/
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_get_multifamily_building test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_get_property_detail
  # Get property detail
  # Get a single Zillow property&#39;s full detail by zpid.
  # @param zpid 
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_get_property_detail test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_get_property_detail_by_url
  # Get property detail by URL
  # Get a single Zillow property&#39;s full detail by its homedetails URL.
  # @param url Full Zillow /homedetails/... URL
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_get_property_detail_by_url test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_list_coverage_markets
  # List coverage markets
  # List Zillow coverage regions (US + Canada).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_list_coverage_markets test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_region_address_suggestions
  # Region/address suggestions
  # Resolve a search term to Zillow regions/addresses.
  # @param query Partial location — city, ZIP, address, neighborhood
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_region_address_suggestions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_search_properties
  # Search properties
  # Search Zillow for for-sale / for-rent / recently-sold properties.
  # @param location City/state, ZIP, address or neighborhood
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status for_sale|for_rent|sold
  # @option opts [Integer] :page 
  # @option opts [String] :sort homes_for_you|newest|price_high_to_low|price_low_to_high|bedrooms|bathrooms|square_feet|lot_size|year_built
  # @option opts [Integer] :price_min 
  # @option opts [Integer] :price_max 
  # @option opts [Integer] :beds_min 
  # @option opts [Float] :baths_min 
  # @option opts [String] :home_type houses|condos|townhomes|apartments|manufactured|lots|multi_family
  # @option opts [Integer] :sqft_min 
  # @option opts [Integer] :sqft_max 
  # @option opts [Integer] :lot_min 
  # @option opts [Integer] :lot_max 
  # @option opts [Integer] :year_built_min 
  # @option opts [Integer] :year_built_max 
  # @option opts [Integer] :hoa_max 
  # @option opts [String] :keywords 
  # @option opts [String] :days_on 
  # @option opts [Float] :north Map bounds for tiling past the 820 cap
  # @option opts [Float] :south 
  # @option opts [Float] :east 
  # @option opts [Float] :west 
  # @return [Object]
  describe 'zillow_search_properties test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_zillow_scraper_health_check
  # Zillow scraper health check
  # Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_zillow_scraper_health_check test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for zillow_zillow_scraper_health_check_head
  # Zillow scraper health check
  # Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'zillow_zillow_scraper_health_check_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
