=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ScrapeBadger
  # Partial update filter rule request.
  class FilterRuleUpdate
    attr_accessor :tag

    attr_accessor :query

    attr_accessor :interval_seconds

    attr_accessor :max_results_per_poll

    attr_accessor :status

    attr_accessor :webhook_url

    attr_accessor :webhook_secret

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'tag' => :'tag',
        :'query' => :'query',
        :'interval_seconds' => :'interval_seconds',
        :'max_results_per_poll' => :'max_results_per_poll',
        :'status' => :'status',
        :'webhook_url' => :'webhook_url',
        :'webhook_secret' => :'webhook_secret'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'tag' => :'String',
        :'query' => :'String',
        :'interval_seconds' => :'Float',
        :'max_results_per_poll' => :'Integer',
        :'status' => :'String',
        :'webhook_url' => :'String',
        :'webhook_secret' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'tag',
        :'query',
        :'interval_seconds',
        :'max_results_per_poll',
        :'status',
        :'webhook_url',
        :'webhook_secret'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ScrapeBadger::FilterRuleUpdate` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ScrapeBadger::FilterRuleUpdate`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'tag')
        self.tag = attributes[:'tag']
      end

      if attributes.key?(:'query')
        self.query = attributes[:'query']
      end

      if attributes.key?(:'interval_seconds')
        self.interval_seconds = attributes[:'interval_seconds']
      end

      if attributes.key?(:'max_results_per_poll')
        self.max_results_per_poll = attributes[:'max_results_per_poll']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'webhook_url')
        self.webhook_url = attributes[:'webhook_url']
      end

      if attributes.key?(:'webhook_secret')
        self.webhook_secret = attributes[:'webhook_secret']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@tag.nil? && @tag.to_s.length > 100
        invalid_properties.push('invalid value for "tag", the character length must be smaller than or equal to 100.')
      end

      if !@tag.nil? && @tag.to_s.length < 1
        invalid_properties.push('invalid value for "tag", the character length must be great than or equal to 1.')
      end

      if !@query.nil? && @query.to_s.length > 1024
        invalid_properties.push('invalid value for "query", the character length must be smaller than or equal to 1024.')
      end

      if !@query.nil? && @query.to_s.length < 1
        invalid_properties.push('invalid value for "query", the character length must be great than or equal to 1.')
      end

      if !@interval_seconds.nil? && @interval_seconds > 86400.0
        invalid_properties.push('invalid value for "interval_seconds", must be smaller than or equal to 86400.0.')
      end

      if !@interval_seconds.nil? && @interval_seconds < 0.1
        invalid_properties.push('invalid value for "interval_seconds", must be greater than or equal to 0.1.')
      end

      if !@max_results_per_poll.nil? && @max_results_per_poll > 100
        invalid_properties.push('invalid value for "max_results_per_poll", must be smaller than or equal to 100.')
      end

      if !@max_results_per_poll.nil? && @max_results_per_poll < 1
        invalid_properties.push('invalid value for "max_results_per_poll", must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^(active|paused)$/)
      if !@status.nil? && @status !~ pattern
        invalid_properties.push("invalid value for \"status\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@tag.nil? && @tag.to_s.length > 100
      return false if !@tag.nil? && @tag.to_s.length < 1
      return false if !@query.nil? && @query.to_s.length > 1024
      return false if !@query.nil? && @query.to_s.length < 1
      return false if !@interval_seconds.nil? && @interval_seconds > 86400.0
      return false if !@interval_seconds.nil? && @interval_seconds < 0.1
      return false if !@max_results_per_poll.nil? && @max_results_per_poll > 100
      return false if !@max_results_per_poll.nil? && @max_results_per_poll < 1
      return false if !@status.nil? && @status !~ Regexp.new(/^(active|paused)$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] tag Value to be assigned
    def tag=(tag)
      if !tag.nil? && tag.to_s.length > 100
        fail ArgumentError, 'invalid value for "tag", the character length must be smaller than or equal to 100.'
      end

      if !tag.nil? && tag.to_s.length < 1
        fail ArgumentError, 'invalid value for "tag", the character length must be great than or equal to 1.'
      end

      @tag = tag
    end

    # Custom attribute writer method with validation
    # @param [Object] query Value to be assigned
    def query=(query)
      if !query.nil? && query.to_s.length > 1024
        fail ArgumentError, 'invalid value for "query", the character length must be smaller than or equal to 1024.'
      end

      if !query.nil? && query.to_s.length < 1
        fail ArgumentError, 'invalid value for "query", the character length must be great than or equal to 1.'
      end

      @query = query
    end

    # Custom attribute writer method with validation
    # @param [Object] interval_seconds Value to be assigned
    def interval_seconds=(interval_seconds)
      if !interval_seconds.nil? && interval_seconds > 86400.0
        fail ArgumentError, 'invalid value for "interval_seconds", must be smaller than or equal to 86400.0.'
      end

      if !interval_seconds.nil? && interval_seconds < 0.1
        fail ArgumentError, 'invalid value for "interval_seconds", must be greater than or equal to 0.1.'
      end

      @interval_seconds = interval_seconds
    end

    # Custom attribute writer method with validation
    # @param [Object] max_results_per_poll Value to be assigned
    def max_results_per_poll=(max_results_per_poll)
      if !max_results_per_poll.nil? && max_results_per_poll > 100
        fail ArgumentError, 'invalid value for "max_results_per_poll", must be smaller than or equal to 100.'
      end

      if !max_results_per_poll.nil? && max_results_per_poll < 1
        fail ArgumentError, 'invalid value for "max_results_per_poll", must be greater than or equal to 1.'
      end

      @max_results_per_poll = max_results_per_poll
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      pattern = Regexp.new(/^(active|paused)$/)
      if !status.nil? && status !~ pattern
        fail ArgumentError, "invalid value for \"status\", must conform to the pattern #{pattern}."
      end

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          tag == o.tag &&
          query == o.query &&
          interval_seconds == o.interval_seconds &&
          max_results_per_poll == o.max_results_per_poll &&
          status == o.status &&
          webhook_url == o.webhook_url &&
          webhook_secret == o.webhook_secret
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [tag, query, interval_seconds, max_results_per_poll, status, webhook_url, webhook_secret].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ScrapeBadger.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
