=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ScrapeBadger
  # Stream monitor response.
  class StreamMonitorResponse
    attr_accessor :id

    attr_accessor :name

    attr_accessor :usernames

    attr_accessor :status

    attr_accessor :status_reason

    attr_accessor :webhook_url

    attr_accessor :webhook_secret_set

    attr_accessor :filter_types

    attr_accessor :credits_per_account_per_day

    attr_accessor :estimated_credits_per_day

    attr_accessor :pricing_tier

    attr_accessor :created_at

    attr_accessor :updated_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'usernames' => :'usernames',
        :'status' => :'status',
        :'status_reason' => :'status_reason',
        :'webhook_url' => :'webhook_url',
        :'webhook_secret_set' => :'webhook_secret_set',
        :'filter_types' => :'filter_types',
        :'credits_per_account_per_day' => :'credits_per_account_per_day',
        :'estimated_credits_per_day' => :'estimated_credits_per_day',
        :'pricing_tier' => :'pricing_tier',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'usernames' => :'Array<String>',
        :'status' => :'String',
        :'status_reason' => :'String',
        :'webhook_url' => :'String',
        :'webhook_secret_set' => :'Boolean',
        :'filter_types' => :'Array<String>',
        :'credits_per_account_per_day' => :'Float',
        :'estimated_credits_per_day' => :'Float',
        :'pricing_tier' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'status_reason',
        :'webhook_url',
        :'filter_types',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ScrapeBadger::StreamMonitorResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ScrapeBadger::StreamMonitorResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'usernames')
        if (value = attributes[:'usernames']).is_a?(Array)
          self.usernames = value
        end
      else
        self.usernames = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'status_reason')
        self.status_reason = attributes[:'status_reason']
      else
        self.status_reason = nil
      end

      if attributes.key?(:'webhook_url')
        self.webhook_url = attributes[:'webhook_url']
      else
        self.webhook_url = nil
      end

      if attributes.key?(:'webhook_secret_set')
        self.webhook_secret_set = attributes[:'webhook_secret_set']
      else
        self.webhook_secret_set = nil
      end

      if attributes.key?(:'filter_types')
        if (value = attributes[:'filter_types']).is_a?(Array)
          self.filter_types = value
        end
      else
        self.filter_types = nil
      end

      if attributes.key?(:'credits_per_account_per_day')
        self.credits_per_account_per_day = attributes[:'credits_per_account_per_day']
      else
        self.credits_per_account_per_day = nil
      end

      if attributes.key?(:'estimated_credits_per_day')
        self.estimated_credits_per_day = attributes[:'estimated_credits_per_day']
      else
        self.estimated_credits_per_day = nil
      end

      if attributes.key?(:'pricing_tier')
        self.pricing_tier = attributes[:'pricing_tier']
      else
        self.pricing_tier = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @usernames.nil?
        invalid_properties.push('invalid value for "usernames", usernames cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @webhook_secret_set.nil?
        invalid_properties.push('invalid value for "webhook_secret_set", webhook_secret_set cannot be nil.')
      end

      if @credits_per_account_per_day.nil?
        invalid_properties.push('invalid value for "credits_per_account_per_day", credits_per_account_per_day cannot be nil.')
      end

      if @estimated_credits_per_day.nil?
        invalid_properties.push('invalid value for "estimated_credits_per_day", estimated_credits_per_day cannot be nil.')
      end

      if @pricing_tier.nil?
        invalid_properties.push('invalid value for "pricing_tier", pricing_tier cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      return false if @usernames.nil?
      return false if @status.nil?
      return false if @webhook_secret_set.nil?
      return false if @credits_per_account_per_day.nil?
      return false if @estimated_credits_per_day.nil?
      return false if @pricing_tier.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          usernames == o.usernames &&
          status == o.status &&
          status_reason == o.status_reason &&
          webhook_url == o.webhook_url &&
          webhook_secret_set == o.webhook_secret_set &&
          filter_types == o.filter_types &&
          credits_per_account_per_day == o.credits_per_account_per_day &&
          estimated_credits_per_day == o.estimated_credits_per_day &&
          pricing_tier == o.pricing_tier &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, usernames, status, status_reason, webhook_url, webhook_secret_set, filter_types, credits_per_account_per_day, estimated_credits_per_day, pricing_tier, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ScrapeBadger.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
