=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'date'
require 'time'

module ScrapeBadger
  # Active subscription details (null when PAYG-only).
  class SubscriptionInfo
    attr_accessor :plan_code

    attr_accessor :plan_title

    attr_accessor :billing_cadence

    attr_accessor :status

    attr_accessor :current_period_start

    attr_accessor :current_period_end

    attr_accessor :cancel_at_period_end

    attr_accessor :cancel_effective_at

    attr_accessor :monthly_credits

    attr_accessor :pending_plan_code

    attr_accessor :pending_plan_title

    attr_accessor :pending_change_effective_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'plan_code' => :'plan_code',
        :'plan_title' => :'plan_title',
        :'billing_cadence' => :'billing_cadence',
        :'status' => :'status',
        :'current_period_start' => :'current_period_start',
        :'current_period_end' => :'current_period_end',
        :'cancel_at_period_end' => :'cancel_at_period_end',
        :'cancel_effective_at' => :'cancel_effective_at',
        :'monthly_credits' => :'monthly_credits',
        :'pending_plan_code' => :'pending_plan_code',
        :'pending_plan_title' => :'pending_plan_title',
        :'pending_change_effective_at' => :'pending_change_effective_at'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'plan_code' => :'String',
        :'plan_title' => :'String',
        :'billing_cadence' => :'String',
        :'status' => :'String',
        :'current_period_start' => :'Time',
        :'current_period_end' => :'Time',
        :'cancel_at_period_end' => :'Boolean',
        :'cancel_effective_at' => :'Time',
        :'monthly_credits' => :'Integer',
        :'pending_plan_code' => :'String',
        :'pending_plan_title' => :'String',
        :'pending_change_effective_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'current_period_start',
        :'current_period_end',
        :'cancel_effective_at',
        :'pending_plan_code',
        :'pending_plan_title',
        :'pending_change_effective_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ScrapeBadger::SubscriptionInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ScrapeBadger::SubscriptionInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'plan_code')
        self.plan_code = attributes[:'plan_code']
      else
        self.plan_code = nil
      end

      if attributes.key?(:'plan_title')
        self.plan_title = attributes[:'plan_title']
      else
        self.plan_title = nil
      end

      if attributes.key?(:'billing_cadence')
        self.billing_cadence = attributes[:'billing_cadence']
      else
        self.billing_cadence = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'current_period_start')
        self.current_period_start = attributes[:'current_period_start']
      end

      if attributes.key?(:'current_period_end')
        self.current_period_end = attributes[:'current_period_end']
      end

      if attributes.key?(:'cancel_at_period_end')
        self.cancel_at_period_end = attributes[:'cancel_at_period_end']
      else
        self.cancel_at_period_end = false
      end

      if attributes.key?(:'cancel_effective_at')
        self.cancel_effective_at = attributes[:'cancel_effective_at']
      end

      if attributes.key?(:'monthly_credits')
        self.monthly_credits = attributes[:'monthly_credits']
      else
        self.monthly_credits = 0
      end

      if attributes.key?(:'pending_plan_code')
        self.pending_plan_code = attributes[:'pending_plan_code']
      end

      if attributes.key?(:'pending_plan_title')
        self.pending_plan_title = attributes[:'pending_plan_title']
      end

      if attributes.key?(:'pending_change_effective_at')
        self.pending_change_effective_at = attributes[:'pending_change_effective_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @plan_code.nil?
        invalid_properties.push('invalid value for "plan_code", plan_code cannot be nil.')
      end

      if @plan_title.nil?
        invalid_properties.push('invalid value for "plan_title", plan_title cannot be nil.')
      end

      if @billing_cadence.nil?
        invalid_properties.push('invalid value for "billing_cadence", billing_cadence cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @plan_code.nil?
      return false if @plan_title.nil?
      return false if @billing_cadence.nil?
      return false if @status.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          plan_code == o.plan_code &&
          plan_title == o.plan_title &&
          billing_cadence == o.billing_cadence &&
          status == o.status &&
          current_period_start == o.current_period_start &&
          current_period_end == o.current_period_end &&
          cancel_at_period_end == o.cancel_at_period_end &&
          cancel_effective_at == o.cancel_effective_at &&
          monthly_credits == o.monthly_credits &&
          pending_plan_code == o.pending_plan_code &&
          pending_plan_title == o.pending_plan_title &&
          pending_change_effective_at == o.pending_change_effective_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [plan_code, plan_title, billing_cadence, status, current_period_start, current_period_end, cancel_at_period_end, cancel_effective_at, monthly_credits, pending_plan_code, pending_plan_title, pending_change_effective_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = ScrapeBadger.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
