=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ScrapeBadger::VintedMobileReadRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ScrapeBadger::VintedMobileReadRequest do
  let(:instance) { ScrapeBadger::VintedMobileReadRequest.new }

  describe 'test an instance of VintedMobileReadRequest' do
    it 'should create an instance of VintedMobileReadRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ScrapeBadger::VintedMobileReadRequest)
    end
  end

  describe 'test attribute "market"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "parameters"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
