=begin
#ScrapeBadger API

#Unified credit-based scraping API. https://docs.scrapebadger.com

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'scrapebadger/api_client'
require 'scrapebadger/api_error'
require 'scrapebadger/version'
require 'scrapebadger/configuration'

# Models
require 'scrapebadger/models/account_info'
require 'scrapebadger/models/billing_log_list_response'
require 'scrapebadger/models/billing_log_response'
require 'scrapebadger/models/filter_rule_create'
require 'scrapebadger/models/filter_rule_delivery_log_list_response'
require 'scrapebadger/models/filter_rule_delivery_log_response'
require 'scrapebadger/models/filter_rule_list_response'
require 'scrapebadger/models/filter_rule_response'
require 'scrapebadger/models/filter_rule_update'
require 'scrapebadger/models/filter_rule_validate_request'
require 'scrapebadger/models/filter_rule_validate_response'
require 'scrapebadger/models/http_validation_error'
require 'scrapebadger/models/portal_api_routers_v1_twitter_filter_rules_filter_rule_pricing_response'
require 'scrapebadger/models/stream_monitor_create'
require 'scrapebadger/models/stream_monitor_list_response'
require 'scrapebadger/models/stream_monitor_response'
require 'scrapebadger/models/stream_monitor_update'
require 'scrapebadger/models/subscription_info'
require 'scrapebadger/models/tweet_delivery_log_list_response'
require 'scrapebadger/models/tweet_delivery_log_response'
require 'scrapebadger/models/validation_error'
require 'scrapebadger/models/validation_error_loc_inner'
require 'scrapebadger/models/webhook_create'
require 'scrapebadger/models/webhook_list_item'
require 'scrapebadger/models/webhook_list_response'
require 'scrapebadger/models/webhook_response'
require 'scrapebadger/models/webhook_test_request'
require 'scrapebadger/models/webhook_test_response'

# APIs
require 'scrapebadger/api/account_api'
require 'scrapebadger/api/amazon_api'
require 'scrapebadger/api/apartments_api'
require 'scrapebadger/api/baidu_api'
require 'scrapebadger/api/bing_api'
require 'scrapebadger/api/chat_gpt_api'
require 'scrapebadger/api/depop_api'
require 'scrapebadger/api/duck_duck_go_api'
require 'scrapebadger/api/e_bay_api'
require 'scrapebadger/api/facebook_api'
require 'scrapebadger/api/gemini_api'
require 'scrapebadger/api/google_api'
require 'scrapebadger/api/idealista_api'
require 'scrapebadger/api/immobiliare_api'
require 'scrapebadger/api/instagram_api'
require 'scrapebadger/api/leboncoin_api'
require 'scrapebadger/api/linked_in_api'
require 'scrapebadger/api/loop_net_api'
require 'scrapebadger/api/perplexity_api'
require 'scrapebadger/api/realtor_api'
require 'scrapebadger/api/reddit_api'
require 'scrapebadger/api/redfin_api'
require 'scrapebadger/api/tik_tok_api'
require 'scrapebadger/api/twitter_api'
require 'scrapebadger/api/vinted_api'
require 'scrapebadger/api/walmart_api'
require 'scrapebadger/api/web_api'
require 'scrapebadger/api/yahoo_api'
require 'scrapebadger/api/yandex_api'
require 'scrapebadger/api/you_tube_api'
require 'scrapebadger/api/zillow_api'

module ScrapeBadger
  class << self
    # Customize default settings for the SDK using block.
    #   ScrapeBadger.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
